### ISSUE TITLE
Apt lock file due to unattended-upgrades causes issues with initial provisioning

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/packer-ubuntu-1604#3]
I could reproduce this issue one time last night, though I've seen a couple other reports of it happening. Basically, Ubuntu 16.04 defaults to running uattended-upgrades automatically (out of the box). What happens is that the first time a box is brought up, unattended-upgrades locks apt (see `/var/lib/dpkg/lock`), and then provisioning scripts error out if they install anything via apt.

The solution I think I'll go with (since I recommend people use the [`geerlingguy.security`](https://galaxy.ansible.com/geerlingguy/security/)) to manage automatic upgrades themselves) is to disable the feature when building via kickstart (as suggested by @gretel):

    d-i pkgsel/update-policy select unattended-upgradesd-i pkgsel/update-policy select unattended-upgrades

See related: https://github.com/mitchellh/vagrant/issues/7155#issuecomment-218849059

**Comment by geerlingguy** [comment]
Testing a new base box build with the changed unattended-upgrades setting.

**Comment by topikito** [comment]
Hi @geerlingguy - Whats the approach then? :)

**Comment by geerlingguy** [comment]
@topikito - I'm uploading the new box version now. I'll be pushing a commit to fix this issue in a couple minutes, once I finish validating the build.

**Comment by topikito** [comment]
Thanks for taking the time to consider my issue @geerlingguy

**Comment by agilethomas** [comment]
In case anyone else comes across this thread, I found a way to solve this problem without disabling unattended-upgrades. What I found was that the apt-daily service was triggering the unattended-upgrades immediately on bootup, and that caused the dpkg lock to occur. The systemd setting that causes it to do that is a timer (which now replaces cron and anacron from what I gather) which is in this file:

/lib/systemd/system/apt-daily.timer
```
...
[Timer]
OnCalendar=*-*-* 6,18:00
Persistent=true
...
```

and the direct cause is the "Persistent" directive, which tells systemd to run the command immediately on bootup if the job was missed while the system was down. Of course, with vagrant, it will always miss this run as long as the image is older than a day. I solved this on my own Xenial vagrant box by adding this file:

 /etc/systemd/system/apt-daily.timer.d/apt-daily.timer.conf

consisting entirely of these 2 lines (which override the setting in the other file):
```
[Timer]
Persistent=false

```

I suspect there may be a better way (I'm new to vagrant) but I can't see how the default ubuntu timer setting is a good idea for vagrant boxes, since they are started and stopped on a more frequent basis than a regular computer. Anytime a vagrant box is brought up, it will run the unattended-upgrades if it missed running it, which will break any apt-get provisioning that gets done. So setting Persistent=false will avoid that.

**Comment by geerlingguy** [comment]
@agilethomas - Awesome! I still kind of like leaving it off by default and having the user enable if desired, mostly because my Vagrant boxes are only intended for local dev, and I always add the caveat that if you consider doing something like `vagrant share`, using public networking, or using the box elsewhere... it's up to you to provide security, and just having automatic updates wouldn't be enough :)
