### ISSUE TITLE
VMWare provider performance issues

### ISSUE THREAD

**Issue by a-fro** [geerlingguy/packer-ubuntu-1604#9]
Hey Jeff. Over the past 6 months I've been trying to track down performance issues our team is facing during local development, using this box with VMware and DrupalVM. This week, I was finally able to isolate it to the VMWare provider. By switching our team to back to VirtualBox, we're seeing dramatic performance improvements (by orders of magnitude). Requests that frequently took 15 seconds or more to complete are now taking hundreds of milliseconds. 

Is there a way that I could help you sort out the cause? I don't know if it's related to your box, vagrant, or the vmware vagrant plugin, and I'm not sure how to begin sorting it out. Using xhprof I was able to figure out that mysql queries were the major bottleneck, though even memcache  appeared to have little to no impact on performance. Switching from NFS to Rsync also had no impact. 

Thanks!

**Comment by geerlingguy** [comment]
Interesting... if it's MySQL queries, then something in MySQL must be hitting a snag. My first two guesses would be disk and memory—I'm assuming you have tried increasing the VM's memory allocation? If you can replicate the scenario, run `top` and `free -m` to see if there's any pressure on the RAM allocated to the VM, or if there's some other process that's killing things.

I haven't encountered this issue, and it's typically more the opposite (but not this extreme) in my testing.

**Comment by geerlingguy** [comment]
I'm going to close this out for now—please reopen if you can figure out any more reasons why it might be failing only on this box. I can't think of anything due to the fact that (a) the box doesn't seem to cause issues elsewhere, and (b) MySQL and most networking setup would be configured on top of this box, and none of the default minimal install settings should be negatively impacted.
